FROM skelter/endor-gorax-tensorflow:1.10.1-gpu-py3-2018-11-07

RUN pip install --upgrade pip

RUN pip install --no-cache-dir --upgrade \
  contextlib2==0.5.5 \
  Cython==0.29.3 \
  jupyter==1.0.0 \
  jupyter-client==5.2.3 \
  jupyter-console==5.2.0 \
  jupyter-core==4.4.0 \
  jupyterlab==0.32.1 \
  jupyterlab-launcher==0.10.5 \
  matplotlib==2.2.2 \
  Pillow==5.4.1
